#!/usr/bin/env bash

function __save_code () {
  code=$?
}

function __status () {
  unadorned_result__=""
  result__=""
  if [ $code != 0 ]
  then
    unadorned_result__="$code"
    result__="$error__$code$no_color__"
  fi
}
