#!/usr/bin/env bash

function __fill () {
  fill=""
  let local fill_size=$COLUMNS-${#unadorned_metadata}-${#unadorned_location}

  if [ "$fill_size" -gt 0 ]
  then
    local unadorned_fill=$( printf "%0${fill_size}d" 0 | sed s/./${fill_char__}/g )
    __prompt_color
    fill="$result__$unadorned_fill$no_color__"
  fi
}
