[ -f /etc/bashrc ] && . /etc/bashrc
[ -f /etc/profile ] && . /etc/profile

export LC_COLLATE=C
export KDEDIR=/usr
export QTDIR=/usr/share/qt3
export EDITOR=vim

. ~/.alias
[ -f ~/.local_alias ] && . ~/.local_alias

if [ "x$TERM" != "x" ]
then
  . ~/.prompt
  twttypow
fi

if [ "$COLORTERM" == "gnome-terminal" ]; then
  export TERM=xterm-256color
fi

export PATH=$PATH:$HOME/settings/bin

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# This line was appended by KDE
# Make sure our customised gtkrc file is loaded.
export GTK2_RC_FILES=$HOME/.gtkrc-2.0

# Ensure that local settings override the defaults
[ -f ~/.local_bashrc ] && . ~/.local_bashrc
