" guifontset should be set in local_vimrc

" Use unicode for special characters
execute 'set listchars+=tab:' . nr2char(187) . nr2char(183) . ',eol:' . nr2char(172)

" Magenta for special characters
highlight NonText guifg=DarkMagenta guibg=black gui=NONE
highlight SpecialKey guifg=DarkMagenta guibg=black gui=NONE

" Turn off useless toolbar
set guioptions-=T

" Turn off menu bar (toggle with CTRL+F11)
set guioptions-=m

" Turn off right-hand scroll-bar
set guioptions-=r
set guioptions-=R

" Turn off left-hand scroll-bar
set guioptions-=l
set guioptions-=L

" Turn off bottom scroll-bar
set guioptions-=b

" CTRL+F11 to toggle the menu bar
nmap <C-F11> :if &guioptions=~'m' \| set guioptions-=m \| else \| set guioptions+=m \| endif<cr>

let extfile = expand("<sfile>:h") . "/.local_gvimrc"

if filereadable(extfile)
  source <sfile>:h/.local_gvimrc
endif
