" Set guifont in ~/.local_gvimrc

" Magenta for special characters
highlight NonText guifg=DarkMagenta guibg=#151515 gui=NONE
highlight SpecialKey guifg=DarkMagenta guibg=#151515 gui=NONE

" Use console dialogs instead of popups
set guioptions+=c

" Turn off useless toolbar
set guioptions-=T

" Turn off right-hand scroll-bar
set guioptions-=r
set guioptions-=R

" Turn off left-hand scroll-bar
set guioptions-=l
set guioptions-=L

" Turn off bottom scroll-bar
set guioptions-=b

" Turn off menu bar (toggle with CTRL+F11)
set guioptions-=m

" CTRL+F11 to toggle the menu bar
nmap <C-F11> :if &guioptions=~'m' \| set guioptions-=m \| else \| set guioptions+=m \| endif<cr>

let extfile = expand("<sfile>:h") . "/.local_gvimrc"

if filereadable(extfile)
  source <sfile>:h/.local_gvimrc
endif
