#!/usr/bin/env bash

# Termwide prompt

function prompt_command () {
  username=$( whoami )
  hostname=$( hostname -s )
  branch=$( git branch --no-color 2>/dev/null | grep '^\*' | sed 's/^.* //' )
  if [ -z $branch ]
  then
    branch=" "
  fi
  directory="${PWD}"

  let promptsize=$( echo -n "--(${branch})---(${directory})--" | wc -c | sed 's/^ *//; s/ *$//' )
  let fillsize=${COLUMNS}-${promptsize}
  fill=''

  if [ "${fillsize}" -lt "0" ]
  then
    let cut=$(( 3 - ${fillsize} ))
    directory="...$( echo -n $directory | sed "s/^.\{$cut}//" )"
  else
    fill=$( printf "%${fillsize}d" 0 | sed s/./-/g )
  fi
}

PROMPT_COMMAND=prompt_command

function twttypow () {
  local GRAY="\[\033[1;30m\]"
  local LIGHT_GRAY="\[\033[0;37m\]"
  local WHITE="\[\033[1;37m\]"
  local NO_COLOUR="\[\033[0m\]"

  local GREEN="\[\033[01;32m\]"
  local LIGHT_BLUE="\[\033[1;34m\]"
  local YELLOW="\[\033[1;33m\]"
  local LIGHT_RED="\[\033[1;31m\]"

  #local ESC="\033k\033\134"
  local ESC=""
  local BASE_COLOR=""
  local PROMPT_CHAR=""
  local BRANCH_COLOR=""

  if [ `whoami` = "root" ]
  then
    BASE_COLOR=$LIGHT_RED
    PROMPT_CHAR="#"
  else
    BASE_COLOR=$YELLOW
    PROMPT_CHAR="$"
  fi

  PS1="\n\
${BASE_COLOR}-${LIGHT_BLUE}-(${GREEN}\${branch}${LIGHT_BLUE})-\
${BASE_COLOR}-\${fill}${LIGHT_BLUE}-(${GREEN}\${directory}${LIGHT_BLUE})-${BASE_COLOR}-\n\
${BASE_COLOR}-${LIGHT_BLUE}-(${BASE_COLOR}\${username}${LIGHT_BLUE}@${BASE_COLOR}\${hostname}${LIGHT_BLUE})-\
${BASE_COLOR}-${NO_COLOUR}${ESC} ${PROMPT_CHAR} "

  PS2="   "
}
