#!/usr/bin/env bash

#   termwide prompt with tty number and power percent
#     by Giles - created 2 November 98
#
#   This is a variant on "termwide" that incorporates the tty number
#   and percent power still in the laptop battery.
#
#   Use of sed with \{$cut\} where $cut is an integer
#   means that this probably now requires a GNU version of sed.

function prompt_command () {

local GREEN="\[\033[01;32m\]"
local YELLOW="\[\033[1;33m\]"
local LIGHT_RED="\[\033[1;31m\]"
local LIGHT_BLUE="\[\033[1;34m\]"

TERMWIDTH=${COLUMNS}

#   Calculate the width of the prompt:

hostnam=$(echo -n $HOSTNAME | sed -e "s/[\.].*//")
#   "whoami" and "pwd" include a trailing newline
usernam=$(whoami)
cur_tty=$(tty | sed -e "s/.*tty\(.*\)/\1/")
branch=$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
export BRANCH=$branch
newPWD="${PWD}"
#power=$(apm | sed -e "s/.*: \([1-9][0-9]*\)%/\1/" | tr -d " ")
#power=$(( `cat /proc/acpi/battery/BAT0/state | grep rem | awk '{}{print $3}'`/480 ))
#state=$(cat /proc/acpi/battery/BAT0/state | grep char | awk '{}{print $3}' | sed 's/unknown/done/')
state="done"

#   Add all the accessories below ...
let promptsize=$(echo -n "--(${usernam}@${hostnam}:${cur_tty}:${branch})---(${PWD})--" \
                 | wc -c | tr -d " ")
let fillsize=${TERMWIDTH}-${promptsize}
fill=""
while [ "$fillsize" -gt "0" ]
do
   fill="${fill}-"
   let fillsize=${fillsize}-1
done

if [ "$fillsize" -lt "0" ]
then
   let cut=3-${fillsize}
   newPWD="...$(echo -n $PWD | sed -e "s/\(^.\{$cut\}\)\(.*\)/\2/")"
fi

case "$state" in
  done)
  color=$GREEN
  ;;
  *)
  if [ $power -lt 30 ]
  then
    if [ $power -lt 10 ]
    then
      color=$LIGHT_RED
    else
      color=$YELLOW
    fi
  else
    color=$LIGHT_BLUE
  fi
esac
}

PROMPT_COMMAND=prompt_command

function twttypow () {

local GRAY="\[\033[1;30m\]"
local LIGHT_GRAY="\[\033[0;37m\]"
local WHITE="\[\033[1;37m\]"
local NO_COLOUR="\[\033[0m\]"
local GREEN="\[\033[01;32m\]"

local LIGHT_BLUE="\[\033[1;34m\]"
local YELLOW="\[\033[1;33m\]"
local LIGHT_RED="\[\033[1;31m\]"

#local ESC="\033k\033\134"
local ESC=""

case $TERM in
  xterm*)
     TITLEBAR='\[\033]0;\u@\h:\w\007\]'
     ;;
  *)
     TITLEBAR=""
     ;;
esac

if [ -n $branch ]
then
  branch_fragment="$LIGHT_BLUE:$GREEN\$branch"
else
  branch_fragment=""
fi

if [ `whoami` = "root" ]
then
  BASE_COLOR=$LIGHT_RED
  PROMPT_CHAR="#"
else
  BASE_COLOR=$YELLOW
  PROMPT_CHAR="$"
fi

PS1="\n$TITLEBAR\
$BASE_COLOR-$LIGHT_BLUE-(\
$BASE_COLOR\$usernam$LIGHT_BLUE@$BASE_COLOR\$hostnam$LIGHT_BLUE:$WHITE\$cur_tty\
$LIGHT_BLUE:$GREEN\$branch\
$LIGHT_BLUE)-$BASE_COLOR-\$fill$LIGHT_BLUE-(\
$GREEN\${newPWD}\
$LIGHT_BLUE)-$BASE_COLOR-\
\n\
$BASE_COLOR-$LIGHT_BLUE-(\
$color$LIGHT_BLUE\
$BASE_COLOR\$(date +%H%M)$LIGHT_BLUE:$BASE_COLOR\$(date \"+%a,%d %b %y\")\
$LIGHT_BLUE)-\
$BASE_COLOR-\
$NO_COLOUR$ESC $PROMPT_CHAR "

#PS2="$LIGHT_BLUE-$YELLOW-$YELLOW-$NO_COLOUR "
PS2="   "
}
