#!/usr/bin/env bash

#   termwide prompt with tty number and power percent
#     by Giles - created 2 November 98
#
#   This is a variant on "termwide" that incorporates the tty number
#   and percent power still in the laptop battery.
#
#   Use of sed with \{$cut\} where $cut is an integer
#   means that this probably now requires a GNU version of sed.

function prompt_command () {

local GREEN="\[\033[01;32m\]"
local YELLOW="\[\033[1;33m\]"
local LIGHT_RED="\[\033[1;31m\]"
local LIGHT_BLUE="\[\033[1;34m\]"

TERMWIDTH=${COLUMNS}

#   Calculate the width of the prompt:

hostnam=$(echo -n $HOSTNAME | sed -e "s/[\.].*//")
#   "whoami" and "pwd" include a trailing newline
usernam=$(whoami)
cur_tty=$(tty | sed -e "s/.*tty\(.*\)/\1/")
newPWD="${PWD}"
#power=$(apm | sed -e "s/.*: \([1-9][0-9]*\)%/\1/" | tr -d " ")
#power=$(( `cat /proc/acpi/battery/BAT0/state | grep rem | awk '{}{print $3}'`/480 ))
#state=$(cat /proc/acpi/battery/BAT0/state | grep char | awk '{}{print $3}' | sed 's/unknown/done/')
state="done"

#   Add all the accessories below ...
let promptsize=$(echo -n "--(${usernam}@${hostnam}:${cur_tty})---(${PWD})--" \
                 | wc -c | tr -d " ")
let fillsize=${TERMWIDTH}-${promptsize}
fill=""
while [ "$fillsize" -gt "0" ]
do
   fill="${fill}-"
   let fillsize=${fillsize}-1
done

if [ "$fillsize" -lt "0" ]
then
   let cut=3-${fillsize}
   newPWD="...$(echo -n $PWD | sed -e "s/\(^.\{$cut\}\)\(.*\)/\2/")"
fi

case "$state" in
	done)
	color=$GREEN
	;;
	*)
	if [ $power -lt 30 ]
	then
		if [ $power -lt 10 ]
		then
			color=$LIGHT_RED
		else
			color=$YELLOW
		fi
	else
		color=$LIGHT_BLUE
	fi
esac
}

PROMPT_COMMAND=prompt_command

function twttypow () {

local GRAY="\[\033[1;30m\]"
local LIGHT_GRAY="\[\033[0;37m\]"
local WHITE="\[\033[1;37m\]"
local NO_COLOUR="\[\033[0m\]"
local GREEN="\[\033[01;32m\]"

local LIGHT_BLUE="\[\033[1;34m\]"
local YELLOW="\[\033[1;33m\]"
local LIGHT_RED="\[\033[1;31m\]"

#local ESC="\033k\033\134"
local ESC=""

case $TERM in
  xterm*)
     TITLEBAR='\[\033]0;\u@\h:\w\007\]'
     ;;
  *)
     TITLEBAR=""
     ;;
esac

if [ `whoami` = "root" ]
then
PS1="\n$TITLEBAR\
$LIGHT_RED-$LIGHT_BLUE-(\
$LIGHT_RED\$usernam$LIGHT_BLUE@$LIGHT_RED\$hostnam$LIGHT_BLUE:$WHITE\$cur_tty\
${LIGHT_BLUE})-${LIGHT_RED}-\${fill}${LIGHT_BLUE}-(\
$GREEN\${newPWD}\
$LIGHT_BLUE)-$LIGHT_RED-\
\n\
$LIGHT_RED-$LIGHT_BLUE-(\
$color$LIGHT_BLUE\
$LIGHT_RED\$(date +%H%M)$LIGHT_BLUE:$LIGHT_RED\$(date \"+%a,%d %b %y\")\
$LIGHT_BLUE)-\
$LIGHT_RED-\
$NO_COLOUR$ESC # "
else
PS1="\n$TITLEBAR\
$YELLOW-$LIGHT_BLUE-(\
$YELLOW\$usernam$LIGHT_BLUE@$YELLOW\$hostnam$LIGHT_BLUE:$WHITE\$cur_tty\
${LIGHT_BLUE})-${YELLOW}-\${fill}${LIGHT_BLUE}-(\
$GREEN\${newPWD}\
$LIGHT_BLUE)-$YELLOW-\
\n\
$YELLOW-$LIGHT_BLUE-(\
$color$LIGHT_BLUE\
$YELLOW\$(date +%H%M)$LIGHT_BLUE:$YELLOW\$(date \"+%a,%d %b %y\")\
$LIGHT_BLUE)-\
$YELLOW-\
$NO_COLOUR$ESC $ "
fi

#PS2="$LIGHT_BLUE-$YELLOW-$YELLOW-$NO_COLOUR "
PS2="   "
}
