if &cp
  set nocp
endif

set encoding=utf-8

set showcmd
set helplang=en
set history=50
set incsearch

set smartindent
set linebreak
set backspace=indent,eol,start
set mouse=a
set ttymouse=xterm2

set printoptions=paper:a4
set ruler
set laststatus=2
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set cursorline

set termencoding=utf-8
set viminfo='20,\"50
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set directory=~/tmp

set modeline
set wildmenu

set listchars=eol:⊸,tab:⊩⊣,extends:▻,precedes:◅,nbsp:░
set foldmethod=marker
set background=dark
set colorcolumn=81

filetype indent on
filetype plugin on
syntax on

" Default colorscheme
colorscheme jellybeans

highlight NonText ctermfg=DarkMagenta ctermbg=black
highlight SpecialKey ctermfg=DarkMagenta ctermbg=black

let python_highlight_all = 1

let mapleader = ','

let extfile = expand("<sfile>:h") . "/.local_vimrc"

if filereadable(extfile)
  source <sfile>:h/.local_vimrc
endif

cabbr a app/mailers/**
cabbr c app/controllers/**
cabbr d db/**
cabbr f config/**
cabbr h app/helpers/**
cabbr j app/assets/javascripts/**
cabbr l lib/**
cabbr m app/models/**
cabbr s app/assets/stylesheets/**
cabbr t spec/**
cabbr tc spec/controllers/**
cabbr tf spec/support/factories/**
cabbr th spec/helpers/**
cabbr tl spec/lib/**
cabbr tm spec/models/**
cabbr ts spec/support/**
cabbr tv spec/views/**
cabbr v app/views/**

call pathogen#infect()
