if &cp
  set nocp
endif

set showcmd
set helplang=en
set history=50
set incsearch

set smartindent
set linebreak
set backspace=indent,eol,start
set mouse=a
set ttymouse=xterm2

set printoptions=paper:a4
set ruler
set laststatus=2
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set cursorline

set termencoding=utf-8
set viminfo='20,\"50
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set directory=~/tmp

set modeline
set wildmenu

set listchars=eol:-,tab:+-,extends:+,precedes:<,nbsp:~
set foldmethod=marker
set background=dark

" Default colorscheme
colorscheme jellybeans

highlight NonText ctermfg=darkmagenta
highlight SpecialKey ctermfg=darkmagenta

filetype indent on
filetype plugin on
syntax on

let python_highlight_all = 1

let mapleader = ','

let extfile = expand("<sfile>:h") . "/.local_vimrc"

if filereadable(extfile)
  source <sfile>:h/.local_vimrc
endif
