#!/usr/bin/env bash
# Inspired by http://www.gilesorr.com/bashprompt/prompts/twttypow.html

for f in ~/settings/sources/prompt.d/*
do
  source $f
done

if [ -d ~/settings/local/prompt.d -a -n "$( shopt -s nullglob; echo ~/settings/local/prompt.d/* )" ]
then
  for f in ~/settings/local/prompt.d/*
  do
    source $f
  done
fi

function prompt_command () {
  __save_code
  __theme
  __metadata
  __location
  __fill
}

function prompt () {
  __colors
  __draw_chars

  PROMPT_COMMAND=prompt_command
  PS1="\n\${metadata}\${fill}\${location}\n\[\$(iterm2_prompt_mark)\]"
  PS2=""
}
