#!/usr/bin/env bash

function __colors () {
  no_color__=$'\001\e[0m\002'

  black__=$'\001\e[0;30m\002'
  red__=$'\001\e[0;31m\002'
  green__=$'\001\e[0;32m\002'
  yellow__=$'\001\e[0;33m\002'
  blue__=$'\001\e[0;34m\002'
  magenta__=$'\001\e[0;35m\002'
  cyan__=$'\001\e[0;36m\002'
  light_gray__=$'\001\e[0;37m\002'

  gray__=$'\001\e[1;30m\002'
  bold_red__=$'\001\e[1;31m\002'
  bold_green__=$'\001\e[1;32m\002'
  bold_yellow__=$'\001\e[1;33m\002'
  bold_blue__=$'\001\e[1;34m\002'
  bold_magenta__=$'\001\e[1;35m\002'
  bold_cyan__=$'\001\e[1;36m\002'
  white__=$'\001\e[1;37m\002'
}

function __draw_chars () {
  fill_char__='─'
  data_start_char__='─┤'
  data_end_char__='├─'
}
