#!/usr/bin/env bash

function __prompt_char () {
  unadorned_result__="$"
  result__="${yellow__}${unadorned_result__}${no_color__}"
  prompt_color__="${gray__}"
  if [ `whoami` = "root" ]
  then
    unadorned_result__="#"
    result__="${red__}${unadorned_result__}${no_color__}"
    prompt_color__="${red__}"
  fi
}
