#!/usr/bin/env bash

function __location () {
  fill=""
  location=""
  let local available_size=${COLUMNS}-${metadata_size}-7  # sizeof(---||--)
  __directory $available_size
  local temp_location=$unadorned_result__
  if [ -z "$unadorned_result__" ]  # Not enough space for location
  then
    let local fill_size=${available_size}+4
    fill=$( printf "%0${fill_size}d" 0 | sed s/./─/g )
    return
  fi

  if [ "$available_size" -ge "${#temp_location}" ]
  then
    if [ "$available_size" -gt "${#temp_location}" ]
    then
      let local fill_size=${available_size}-${#temp_location}
      fill=$( printf "%0${fill_size}d" 0 | sed s/./─/g )
    fi

    location="${blue__}─┤${no_color__}$result__${blue__}├─${no_color__}"
  fi
}
