#!/usr/bin/env bash

function __location () {
  __directory
  local temp_location=$result__
  let local location_size=$( echo -n "$unadorned_result__" | wc -c | sed 's/^ *//; s/ *$//' )+4
  let local promptsize=3
  let local fillsize=${COLUMNS}-${promptsize}-${metadata_size}-${location_size}
  fill=""
  if [ "$fillsize" -lt "0" ]
  then
    let local cut=3-1-${fillsize}
    temp_location="...$( echo -n $temp_location | sed "s@/.\{$cut\}@@" )"
  else
    fill=$( printf "%0${fillsize}d" 0 | sed s/./─/g )
  fi
  location="${blue__}─┤${no_color__}$temp_location${blue__}├─${no_color__}"
}
