#!/usr/bin/env bash

function __location () {
  unadorned_location=""
  location=""

  __hostname
  local hostname=$result__
  local unadorned_hostname=$unadorned_result__

  let local available_size=$COLUMNS-${#unadorned_metadata}-${#data_start_char__}-${#unadorned_hostname}-1  # reserve at least one character for fill
  if [ "$available_size" -lt 0 ]
  then
    return  # Not enough space for hostname
  fi

  let local available_size=$COLUMNS-${#unadorned_metadata}-${#data_start_char__}-${#unadorned_hostname}-2
  __directory $available_size
  local directory=$result__
  local unadorned_directory=$unadorned_result__

  if [ -z "$directory" ]
  then
    unadorned_location="${data_start_char__}$unadorned_hostname"
    location="$highlight__$data_start_char__$no_color__$hostname$no_color__"
  else
    __prompt_color
    unadorned_location="${data_start_char__}$unadorned_hostname:$unadorned_directory"
    location="$highlight__$data_start_char__$hostname$result__:$directory$no_color__"
  fi
}
