#!/usr/bin/env bash

function __metadata () {
  let metadata_size=0
  metadata=""
  __git
  if [ -n "$unadorned_result__" ]
  then
    let metadata_size=$( echo -n "$unadorned_result__" | wc -c | sed 's/^ *//; s/ *$//' )+4
    metadata="${blue__}${data_left_char__}${no_color__}$result__${blue__}${data_right_char__}${no_color__}"
  fi
}
