#!/usr/bin/env bash

function __metadata () {
  __status
  local status=$result__
  local unadorned_status=$unadorned_result__

  __git
  local revision=$result__
  local unadorned_revision=$unadorned_result__

  if [ -n "$revision" -a -n "$status" ]
  then
    unadorned_metadata="$unadorned_revision $unadorned_status$data_end_char__"
    metadata="$revision $status$blue__$data_end_char__$no_color__"
  elif [ -n "$revision" ]
  then
    unadorned_metadata="$unadorned_revision$data_end_char__"
    metadata="$revision$blue__$data_end_char__$no_color__"
  elif [ -n "$status" ]
  then
    unadorned_metadata="$unadorned_status$data_end_char__"
    metadata="$status$blue__$data_end_char__$no_color__"
  else
    unadorned_metadata=""
    metadata=""
  fi
}
