#!/usr/bin/env bash

export EDITOR=vim

# Ensure that files are sorted case sensitive
export LC_COLLATE=C

# Modify PATHs without introducing duplicates
path_append() {
  local var=$1
  shift

  while (( $# ))
  do
    if [ -d "$1" ]
    then
      if [ -z "${!var}" ]
      then
        export "$var"="$1"
      else
        if [[ ":${!var}:" != *":$1:"* ]]
        then
          export "$var"="${!var}:$1"
        fi
      fi
    fi
    shift
  done
}

path_prepend() {
  local var=$1
  shift

  while (( $# ))
  do
    if [ -d "$1" ]
    then
      if [ -z "${!var}" ]
      then
        export "$var"="$1"
      else
        if [[ ":${!var}:" != *":$1:"* ]]
        then
          export "$var"="$1:${!var}"
        fi
      fi
    fi
    shift
  done
}

path_append "PATH" "$HOME/settings/bin" "$HOME/settings/local_sources/bin"
path_append "CDPATH" "$HOME" "$HOME/work/projects"

# Prepend cd to directory names automatically
shopt -s autocd
# Correct spelling errors during tab-completion
shopt -s dirspell
# Correct spelling errors in arguments supplied to cd
shopt -s cdspell

if [ "$COLORTERM" == "gnome-terminal" ]; then
  export TERM=xterm-256color
fi

# Avoid duplicate entries
export HISTCONTROL="erasedups:ignoreboth"

# Huge history. Doesn't appear to slow things down, so why not?
export HISTSIZE=500000
export HISTFILESIZE=100000

# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

# Useful timestamp format
HISTTIMEFORMAT='%F %T '

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Prevent file overwrite on stdout redirection
set -o noclobber

## SMARTER TAB-COMPLETION (Readline bindings) ##
# Perform file completion in a case insensitive fashion
# bind "set completion-ignore-case on"

# Treat hyphens and underscores as equivalent
# bind "set completion-map-case on"

# Display matches for ambiguous patterns at first tab press
# bind "set show-all-if-ambiguous on"
