#!/usr/bin/env bash
# Inspired by http://www.gilesorr.com/bashprompt/prompts/twttypow.html

for f in ~/settings/config_sources/prompt.d/*
do
  source $f
done

if [ -d ~/settings/config_local/prompt.d -a -n "$( shopt -s nullglob; echo "~/settings/config_local/prompt.d/*" )" ]
then
  for f in ~/settings/config_local/prompt.d/*
  do
    source $f
  done
fi

function prompt_command () {
  __system
  __metadata
  __location

  __prompt_char
  prompt_char=$result__
}

function prompt () {
  __colors
  __draw_chars

  PROMPT_COMMAND=prompt_command
  PS1="\n\
\${prompt_color__}\${top_left_char__}\${metadata}\
\${prompt_color__}\${fill_char__}\${fill}\${location}\
\${prompt_color__}\${end_char__}\n\
\${bottom_left_char__}\${system}\
\${prompt_color__}\${end_char__} \${prompt_char} "
  PS2="   "
}
