#!/usr/bin/env bash

if [ -d ~/settings/config_local/bashrc.d -a -n "$( shopt -s nullglob; echo "~/settings/config_local/bashrc.d/*" )" ]
then
  for f in ~/settings/config_local/bashrc.d/*
  do
    source $f
  done
fi
